# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dataViewer.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormDataViewer(object):
    def setupUi(self, FormDataViewer):
        FormDataViewer.setObjectName("FormDataViewer")
        FormDataViewer.resize(1110, 678)
        self.gridLayout_8 = QtWidgets.QGridLayout(FormDataViewer)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.splitter_3 = QtWidgets.QSplitter(FormDataViewer)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.wavePlotLayout = GraphicsLayoutWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wavePlotLayout.sizePolicy().hasHeightForWidth())
        self.wavePlotLayout.setSizePolicy(sizePolicy)
        self.wavePlotLayout.setMinimumSize(QtCore.QSize(500, 300))
        self.wavePlotLayout.setObjectName("wavePlotLayout")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.splitter_2)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.South)
        self.tabWidget_3.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_3.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget_3.setDocumentMode(False)
        self.tabWidget_3.setTabsClosable(False)
        self.tabWidget_3.setMovable(True)
        self.tabWidget_3.setTabBarAutoHide(False)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spectrumPlotLayout = GraphicsLayoutWidget(self.tab_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spectrumPlotLayout.sizePolicy().hasHeightForWidth())
        self.spectrumPlotLayout.setSizePolicy(sizePolicy)
        self.spectrumPlotLayout.setObjectName("spectrumPlotLayout")
        self.gridLayout_2.addWidget(self.spectrumPlotLayout, 0, 0, 1, 1)
        self.tabWidget_3.addTab(self.tab_6, "")
        self.scrollArea = QtWidgets.QScrollArea(self.splitter_3)
        self.scrollArea.setMaximumSize(QtCore.QSize(360, 16777215))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 360, 660))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.splitter = QtWidgets.QSplitter(self.scrollAreaWidgetContents_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(250, 0))
        self.tabWidget_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 1, 1, 1)
        self.lineEditIP = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditIP.setObjectName("lineEditIP")
        self.gridLayout_3.addWidget(self.lineEditIP, 1, 0, 1, 1)
        self.lineEditPort = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditPort.setObjectName("lineEditPort")
        self.gridLayout_3.addWidget(self.lineEditPort, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 2, 1, 1, 1)
        self.lineEditVar = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditVar.setObjectName("lineEditVar")
        self.gridLayout_3.addWidget(self.lineEditVar, 3, 0, 1, 1)
        self.doubleSpinBoxSize = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxSize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSize.setDecimals(0)
        self.doubleSpinBoxSize.setMinimum(64.0)
        self.doubleSpinBoxSize.setMaximum(10000000.0)
        self.doubleSpinBoxSize.setProperty("value", 4096.0)
        self.doubleSpinBoxSize.setObjectName("doubleSpinBoxSize")
        self.gridLayout_3.addWidget(self.doubleSpinBoxSize, 3, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 4, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 4, 1, 1, 1)
        self.comboBoxVarType = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxVarType.setObjectName("comboBoxVarType")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.comboBoxVarType.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxVarType, 5, 0, 1, 1)
        self.comboBoxByteOrder = QtWidgets.QComboBox(self.tab_3)
        self.comboBoxByteOrder.setObjectName("comboBoxByteOrder")
        self.comboBoxByteOrder.addItem("")
        self.comboBoxByteOrder.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxByteOrder, 5, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 6, 0, 1, 1)
        self.spinBoxSampleRate = QtWidgets.QSpinBox(self.tab_3)
        self.spinBoxSampleRate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxSampleRate.setMinimum(1)
        self.spinBoxSampleRate.setMaximum(900000000)
        self.spinBoxSampleRate.setProperty("value", 1)
        self.spinBoxSampleRate.setDisplayIntegerBase(10)
        self.spinBoxSampleRate.setObjectName("spinBoxSampleRate")
        self.gridLayout_3.addWidget(self.spinBoxSampleRate, 7, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.tab_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 6, 1, 1, 1)
        self.doubleSpinBoxSampleFreq = QtWidgets.QDoubleSpinBox(self.tab_3)
        self.doubleSpinBoxSampleFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxSampleFreq.setDecimals(1)
        self.doubleSpinBoxSampleFreq.setMaximum(9999990.0)
        self.doubleSpinBoxSampleFreq.setSingleStep(0.1)
        self.doubleSpinBoxSampleFreq.setProperty("value", 1.0)
        self.doubleSpinBoxSampleFreq.setObjectName("doubleSpinBoxSampleFreq")
        self.gridLayout_3.addWidget(self.doubleSpinBoxSampleFreq, 7, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.toolButtonAdd = QtWidgets.QToolButton(self.tab_3)
        self.toolButtonAdd.setObjectName("toolButtonAdd")
        self.horizontalLayout.addWidget(self.toolButtonAdd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidgetVarList = QtWidgets.QListWidget(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetVarList.sizePolicy().hasHeightForWidth())
        self.listWidgetVarList.setSizePolicy(sizePolicy)
        self.listWidgetVarList.setMinimumSize(QtCore.QSize(0, 70))
        self.listWidgetVarList.setMaximumSize(QtCore.QSize(16777215, 140))
        self.listWidgetVarList.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidgetVarList.setObjectName("listWidgetVarList")
        self.verticalLayout.addWidget(self.listWidgetVarList)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonStart = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonStart.setObjectName("pushButtonStart")
        self.gridLayout.addWidget(self.pushButtonStart, 0, 0, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayout.addWidget(self.pushButtonStop, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.widgetChannels = QtWidgets.QWidget(self.tab_3)
        self.widgetChannels.setObjectName("widgetChannels")
        self.verticalLayout.addWidget(self.widgetChannels)
        spacerItem1 = QtWidgets.QSpacerItem(20, 72, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_16 = QtWidgets.QLabel(self.tab_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_4.addWidget(self.label_16)
        self.comboBoxHarmonicChannel = QtWidgets.QComboBox(self.tab_2)
        self.comboBoxHarmonicChannel.setObjectName("comboBoxHarmonicChannel")
        self.horizontalLayout_4.addWidget(self.comboBoxHarmonicChannel)
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        self.spinBoxDecimals = QtWidgets.QSpinBox(self.tab_2)
        self.spinBoxDecimals.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBoxDecimals.setSuffix("")
        self.spinBoxDecimals.setMaximum(9)
        self.spinBoxDecimals.setProperty("value", 1)
        self.spinBoxDecimals.setObjectName("spinBoxDecimals")
        self.horizontalLayout_4.addWidget(self.spinBoxDecimals)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.widgetHarmonic = DataTableWidget(self.tab_2)
        self.widgetHarmonic.setObjectName("widgetHarmonic")
        self.verticalLayout_5.addWidget(self.widgetHarmonic)
        self.verticalLayout_5.setStretch(1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout_7.addWidget(self.splitter, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_8.addWidget(self.splitter_3, 0, 0, 1, 1)

        self.retranslateUi(FormDataViewer)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FormDataViewer)

    def retranslateUi(self, FormDataViewer):
        _translate = QtCore.QCoreApplication.translate
        FormDataViewer.setWindowTitle(_translate("FormDataViewer", "Form"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_6), _translate("FormDataViewer", "FFT"))
        self.label_9.setText(_translate("FormDataViewer", "IP"))
        self.label_8.setText(_translate("FormDataViewer", "端口(Port)"))
        self.lineEditIP.setText(_translate("FormDataViewer", "127.0.0.1"))
        self.lineEditPort.setText(_translate("FormDataViewer", "4823"))
        self.label_11.setText(_translate("FormDataViewer", "变量(Variable)"))
        self.label_10.setText(_translate("FormDataViewer", "长度(Length-Bytes)"))
        self.label_21.setText(_translate("FormDataViewer", "变量类型(Variable Type)"))
        self.label_22.setText(_translate("FormDataViewer", "字节序(Byte Order)"))
        self.comboBoxVarType.setItemText(0, _translate("FormDataViewer", "u8"))
        self.comboBoxVarType.setItemText(1, _translate("FormDataViewer", "s8"))
        self.comboBoxVarType.setItemText(2, _translate("FormDataViewer", "u16"))
        self.comboBoxVarType.setItemText(3, _translate("FormDataViewer", "s16"))
        self.comboBoxVarType.setItemText(4, _translate("FormDataViewer", "u32"))
        self.comboBoxVarType.setItemText(5, _translate("FormDataViewer", "s32"))
        self.comboBoxVarType.setItemText(6, _translate("FormDataViewer", "u64"))
        self.comboBoxVarType.setItemText(7, _translate("FormDataViewer", "s64"))
        self.comboBoxVarType.setItemText(8, _translate("FormDataViewer", "float"))
        self.comboBoxVarType.setItemText(9, _translate("FormDataViewer", "double"))
        self.comboBoxByteOrder.setItemText(0, _translate("FormDataViewer", "Little endians"))
        self.comboBoxByteOrder.setItemText(1, _translate("FormDataViewer", "Big endians"))
        self.label_5.setText(_translate("FormDataViewer", "采样频率(Sample Rate)"))
        self.spinBoxSampleRate.setSuffix(_translate("FormDataViewer", " Hz"))
        self.label_23.setText(_translate("FormDataViewer", "自动读取"))
        self.doubleSpinBoxSampleFreq.setSuffix(_translate("FormDataViewer", " s"))
        self.toolButtonAdd.setText(_translate("FormDataViewer", "+"))
        self.pushButtonStart.setText(_translate("FormDataViewer", "启动"))
        self.pushButtonStop.setText(_translate("FormDataViewer", "停止"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("FormDataViewer", "连接设置"))
        self.label_16.setText(_translate("FormDataViewer", "变量："))
        self.label_24.setText(_translate("FormDataViewer", "Decimals:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("FormDataViewer", "谐波分析"))
from pyqtgraph import GraphicsLayoutWidget
from qtpandas_widget.view import DataTableWidget
